AreasWithAuth.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AreasWithAuth.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

AreasWithAuth.Web/Areas/Admin/Controllers/ExperienceController.cs
using AreasWithAuth.Data;
using AreasWithAuth.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AreasWithAuth.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExperienceController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExperienceController(ApplicationDbContext db)
        {
            _db= db;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAll()
        {
            return Json(new { data = _db.Experiences.ToList<Experience>() }); ;
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(Experience experience) { 
        
            _db.Experiences.Add(experience);
            _db.SaveChanges();
            return Json(experience);
        }
    }
}

AreasWithAuth.Web/Areas/Admin/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using static System.Net.Mime.MediaTypeNames;
using Image = System.Drawing.Image;

namespace AreasWithAuth.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProfileController : Controller
    {
        private readonly IWebHostEnvironment _env;
        public ProfileController(IConfiguration configuration, IWebHostEnvironment env)
        {
            _env = env;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ImageSave(string imgBase64)
        {
            Console.WriteLine(imgBase64);
            Image img;
            //img = Image.FromStream();
            if (!string.IsNullOrEmpty(imgBase64))
            {
                byte[] imgConvert = Convert.FromBase64String(imgBase64.Substring(22));
                var ms = new MemoryStream(imgConvert, 0, imgConvert.Length);
                ms.Write(imgConvert, 0, imgConvert.Length);
                 img = Image.FromStream(ms, true);
                string filename = Guid.NewGuid() + ".png";
                img.Save(_env.ContentRootPath + "/dosyalar/profilephoto/" + filename);
                
            }

            return Json(imgBase64);
        }
    }
}

AreasWithAuth.Web/Areas/Admin/Controllers/UserController.cs
using AreasWithAuth.Data;
using AreasWithAuth.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AreasWithAuth.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;

        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(AppUser appUser)
        {
            AppUser user = _db.AppUsers.Include(u => u.AppUserRole).FirstOrDefault(u => u.UserName == appUser.UserName && u.Password == appUser.Password && u.IsActive == true);
            if (user != null)
            {
                List<Claim> claims= new List<Claim>();
                claims.Add(new Claim (ClaimTypes.Name,user.UserName ));
                claims.Add(new Claim(ClaimTypes.Email, user.Email));
                claims.Add(new Claim(ClaimTypes.Role, user.AppUserRole.Name));

                var claimsIdentity= new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                
                
            }
            return Json(user);
        }
    }
}

AreasWithAuth.Web/Controllers/HomeController.cs
using AreasWithAuth.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AreasWithAuth.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
    }
}

AreasWithAuth.Web/Areas/Admin/Views/Dashboard/Index.cshtml
@{

}

AreasWithAuth.Web/Areas/Admin/Views/Experience/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a class="btn btn-primary" id="btnYeniEkle">Yeni Ekle</a>
<table id="tablo">
    <thead>
        <tr>
            <th>Id</th>
            <th>Location</th>
            <th>Company Name</th>
            <th>Position</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
    </tbody>

</table>


<div class="modal fade" id="modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" role="dialog" aria-labelledby="modalTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitleId">Tecrübe Ekle</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3 row">
                    <label for="inputName" class="col-4 col-form-label">Company Name</label>
                    <div class="col-8">
                        <input type="text" class="form-control" id="txtCompanyName" placeholder="Company name">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputName" class="col-4 col-form-label">Location</label>
                    <div class="col-8">
                        <input type="text" class="form-control" id="txtLocation" placeholder="Location">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputName" class="col-4 col-form-label">Position</label>
                    <div class="col-8">
                        <input type="text" class="form-control" id="txtPosition" placeholder="Position">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputName" class="col-4 col-form-label">Description</label>
                    <div class="col-8">
                        <input type="text" class="form-control" id="txtDescription" placeholder="Description">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="inputName" class="col-4 col-form-label">Start Date</label>
                    <div class="col-8">
                        <input type="date" class="form-control" id="dateStartDate" placeholder="Start Date">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputName" class="col-4 col-form-label">End Date</label>
                    <div class="col-8">
                        <input type="date" class="form-control" id="dateEndDate" placeholder="End Date">
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                <button type="button" id="btnKaydet" class="btn btn-primary">Kaydet</button>
                <button type="button" id="btnGuncelle" class="btn btn-primary">Güncelle</button>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script type="text/javascript">

        $("#btnYeniEkle").click(function () {
            $("#modal").modal('show');
            $("#btnGuncelle").hide();
        });


        $("#btnKaydet").click(function () {

            var veri = {
                companyName: $("#txtCompanyName").val(),
                location: $("#txtLocation").val(),
                position: $("#txtPosition").val(),
                description: $("#txtDescription").val(),
                startDate: $("#dateStartDate").val(),
                endDate: $("#dateEndDate").val()
            };

            $.ajax({
                url: "@Url.Action("Add","Experience")",
                type: "POST",
                data: veri,
                success: function (res) {
                    $("#modal").modal('hide');
                    DataTable.ajax.reload();
                }
            });




        });




        var DataTable = $("#tablo").DataTable({
            ajax: "@Url.Action("GetAll","Experience")",
            columns: [
                { data: 'id' },
                { data: 'location' },
                { data: 'companyName' },
                { data: 'position' },
                { data: 'description' },
                { data: 'startDate' },
                { data: 'endDate' },
                {
                    data: 'id', render: function (data) {
                        return `<a class="btn btn-danger">Sil</a>`
                    }
                }
            ],

            columnDefs: [
                {
                    target: 5,
                    render: DataTable.render.date(),
                },
                {
                    target: 6,
                    render: DataTable.render.date(),
                },
                

            ],

        });


    </script>
}

AreasWithAuth.Web/Areas/Admin/Views/User/Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <!--Stylesheet-->
    <style media="screen">
        *,
        *:before,
        *:after {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #080710;
        }

        .background {
            width: 430px;
            height: 520px;
            position: absolute;
            transform: translate(-50%,-50%);
            left: 50%;
            top: 50%;
        }

            .background .shape {
                height: 200px;
                width: 200px;
                position: absolute;
                border-radius: 50%;
            }

        .shape:first-child {
            background: linear-gradient( #1845ad, #23a2f6 );
            left: -80px;
            top: -80px;
        }

        .shape:last-child {
            background: linear-gradient( to right, #ff512f, #f09819 );
            right: -30px;
            bottom: -80px;
        }

        form {
            height: 520px;
            width: 400px;
            background-color: rgba(255,255,255,0.13);
            position: absolute;
            transform: translate(-50%,-50%);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255,255,255,0.1);
            box-shadow: 0 0 40px rgba(8,7,16,0.6);
            padding: 50px 35px;
        }

            form * {
                font-family: 'Poppins',sans-serif;
                color: #ffffff;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }

            form h3 {
                font-size: 32px;
                font-weight: 500;
                line-height: 42px;
                text-align: center;
            }

        label {
            display: block;
            margin-top: 30px;
            font-size: 16px;
            font-weight: 500;
        }

        input {
            display: block;
            height: 50px;
            width: 100%;
            background-color: rgba(255,255,255,0.07);
            border-radius: 3px;
            padding: 0 10px;
            margin-top: 8px;
            font-size: 14px;
            font-weight: 300;
        }

        ::placeholder {
            color: #e5e5e5;
        }

        button {
            margin-top: 50px;
            width: 100%;
            background-color: #ffffff;
            color: #080710;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border-radius: 5px;
            cursor: pointer;
        }

        .social {
            margin-top: 30px;
            display: flex;
        }

            .social div {
                background: red;
                width: 150px;
                border-radius: 3px;
                padding: 5px 10px 10px 5px;
                background-color: rgba(255,255,255,0.27);
                color: #eaf0fb;
                text-align: center;
            }

                .social div:hover {
                    background-color: rgba(255,255,255,0.47);
                }

            .social .fb {
                margin-left: 25px;
            }

            .social i {
                margin-right: 4px;
            }

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form id="frm" >
        <h3>Login Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Email or Phone" id="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password">

        <input type="button" id="btnLogin" value="LOG IN" >
        <div class="social">
            <div class="go"><i class="fab fa-google"></i>  Google</div>
            <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div>
    </form>

    <script type="text/javascript">
    
        $("#btnLogin").click(function() {
             
            
            var veri={
            userName: $("#username").val(),
            password: $("#password").val()
        }

           console.log(veri);

        $.ajax({
            type:"POST",
            data:veri,
            url:"@Url.Action("Login","User")",
            success:function(res)
            {
                if(res==null)
                {
                  
                    alert("hatalı kullanıcı");
                }
                else
                {
                    location.href="@Url.Action("Index","Dashboard")";
                }
            }
        });




        });

       


        
    </script>
</body>
</html>

AreasWithAuth.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

	<!-- Basic -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Demo Resume | Porto - Multipurpose Website Template</title>

	<meta name="keywords" content="WebSite Template" />
	<meta name="description" content="Porto - Multipurpose Website Template">
	<meta name="author" content="okler.net">

	<!-- Favicon -->
	<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" href="img/apple-touch-icon.png">

	<!-- Mobile Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

	<!-- Web Fonts  -->
	<link id="googleFonts" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800&display=swap" rel="stylesheet" type="text/css">

	<!-- Vendor CSS -->
	<link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="vendor/fontawesome-free/css/all.min.css">
	<link rel="stylesheet" href="vendor/animate/animate.compat.css">
	<link rel="stylesheet" href="vendor/simple-line-icons/css/simple-line-icons.min.css">
	<link rel="stylesheet" href="vendor/owl.carousel/assets/owl.carousel.min.css">
	<link rel="stylesheet" href="vendor/owl.carousel/assets/owl.theme.default.min.css">
	<link rel="stylesheet" href="vendor/magnific-popup/magnific-popup.min.css">

	<!-- Theme CSS -->
	<link rel="stylesheet" href="css/theme.css">
	<link rel="stylesheet" href="css/theme-elements.css">
	<link rel="stylesheet" href="css/theme-blog.css">
	<link rel="stylesheet" href="css/theme-shop.css">

	<!-- Demo CSS -->
	<link rel="stylesheet" href="css/demos/demo-resume.css">

	<!-- Skin CSS -->
	<link id="skinCSS" rel="stylesheet" href="css/skins/skin-resume.css">

	<!-- Theme Custom CSS -->
	<link rel="stylesheet" href="css/custom.css">

	<!-- Head Libs -->
	<script src="vendor/modernizr/modernizr.min.js"></script>

</head>
<body data-plugin-scroll-spy data-plugin-options="{'target': '.wrapper-spy'}">

	<div class="body">
		<header id="header" class="header-floating-icons" data-plugin-options="{'stickyEnabled': false, 'stickyEnableOnBoxed': false, 'stickyEnableOnMobile': false, 'stickyStartAt': 0, 'stickySetTop': '60px', 'stickyChangeLogo': false}">
			<div class="header-body bg-transparent">
				<div class="header-container container">
					<div class="header-row">
						<div class="header-column">
							<div class="header-row">
								<div class="header-nav pt-1">
									<div class="header-nav-main">
										<nav class="wrapper-spy collapse">
											<ul class="nav" id="mainNav">
												<li>
													<a data-hash href="#about-me" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-home icons"></i>
														<span class="custom-tooltip text-color-dark">About Me</span>
													</a>
												</li>
												<li>
													<a data-hash href="#experience" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-eye icons"></i>
														<span class="custom-tooltip text-color-dark">Experience</span>
													</a>
												</li>
												<li>
													<a data-hash href="#education" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-briefcase icons"></i>
														<span class="custom-tooltip text-color-dark">Education</span>
													</a>
												</li>
												<li>
													<a data-hash href="#skills" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-graduation icons"></i>
														<span class="custom-tooltip text-color-dark">Skills</span>
													</a>
												</li>
												<li>
													<a data-hash href="#portfolio" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-diamond icons"></i>
														<span class="custom-tooltip text-color-dark">Portfolio</span>
													</a>
												</li>
												<li>
													<a data-hash data-hash-offset="0" data-hash-offset-lg="100" href="#recommendations" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-pencil icons"></i>
														<span class="custom-tooltip text-color-dark">Recommendations</span>
													</a>
												</li>
												<li>
													<a data-hash href="#blog" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-bubbles icons"></i>
														<span class="custom-tooltip text-color-dark">Blog</span>
													</a>
												</li>
												<li>
													<a data-hash href="#say-hello" class="nav-link text-color-dark bg-color-primary">
														<i class="icon-envelope-open icons"></i>
														<span class="custom-tooltip text-color-dark">Say Hello</span>
													</a>
												</li>
											</ul>
										</nav>
									</div>
									<button class="btn header-btn-collapse-nav text-color-dark border-radius-0" data-bs-toggle="collapse" data-bs-target=".header-nav-main nav">
										<i class="fas fa-bars"></i>
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>

		<div role="main" class="main">

			@RenderBody();

			<footer id="footer" class="m-0 p-0">
				<div class="footer-copyright bg-color-light m-0">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 m-0">
								<p  class="custom-text-color-2">© Copyright 2022. All Rights Reserved.</p>
							</div>
						</div>
					</div>
				</div>
			</footer>
		</div>

		<!-- Vendor -->
		<script src="vendor/plugins/js/plugins.min.js"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="js/theme.js"></script>

		<!-- Current Page Vendor and Views -->
		<script src="js/views/view.contact.js"></script>

		<!-- Demo -->
		<script src="js/demos/demo-resume.js"></script>

		<!-- Theme Custom -->
		<script src="js/custom.js"></script>

		<!-- Theme Initialization Files -->
		<script src="js/theme.init.js"></script>

       
        


		@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

AreasWithAuth.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Site Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin Panel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            
                            <a asp-action="Index" class="nav-link text-dark" asp-controller="Experience" asp-area="Admin">Experience Yönetimi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Kutuphane.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>